// Generated by CoffeeScript 1.7.1
(function() {
  var language, message, output;

  language = "CoffeeScript";

  message = "Hello " + language + " +   watch";

  output = function(comment) {
    return console.log(comment);
  };

  output(message);

}).call(this);
